
quarkus:
  http:
#    port: 8083
  smallrye-openapi:
    info-title: supplier-svc
    auto-add-security-requirement: false

  swagger-ui:
    always-include: true
    path: /swagger


  datasource:
    db-kind: postgresql
    jdbc:
      # Is set to 5 as we have 112 connections in total
      initial-size: 1
      min-size: 1
      max-size: 5
      url: ${MTOGO_DB_BASE_URL}/supplier_svc_db
    username: ${MTOGO_DB_USERNAME}
    password: ${MTOGO_DB_PASSWORD}

    transaction-manager:
      default-transaction-timeout: 300s
  hibernate-orm:
    database:
      generation: update


#  rest-client:
#    product-dk.vv.mtogo.supplier.msvc.api:
#      url: ${MTOGO_PRODUCT_SERVICE_URL}

"%dev":
  quarkus:
    log:
      level: INFO
      console:
        json: false
    http:
      port: 8086

    hibernate-orm:
      database:
        default-schema: "supplier"

"%prod":
  quarkus:
    hibernate-orm:
      database:
        default-schema: "supplier"